# @package agent
_target_: agent.dac.DACAgent
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
num_expl_steps: 2000
hidden_dim: ${suite.hidden_dim}
feature_dim: 512
stddev_schedule: 0.1
stddev_clip: 0.3
augment: True
use_actions: false
suite_name: ${suite.name}
obs_type: ${obs_type}
bc_weight_type: ${bc_weight_type}
offset_mask: [1, 1, 1, 1] # Key Insertion - [0.3, 1, 0], Bagel - [0, 0, 1, 0, 0, 0], PegInCup - [1, 1, 0], MetaWorld envs - [1, 1, 1, 1]